server:
  port: 9904
#服务名称
spring:
  application:
    name: pay
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1000
  profiles:
    include: gobal
  rabbitmq:
    host: 192.168.247.134
    port: 5972
    username: admin
    password: admin
    virtual-host: /pay

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${fx.eureka.port}/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

