server:
  port: 80
#服务名称
spring:
  application:
    name: oauth
  profiles:
    include: gobal
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/wxshop?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1000
mybatis:
  mapper-locations: classpath:mapper/*xml
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${fx.eureka.port}/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


